name: "go-pg"

services:
    golang:
        build: ./
        container_name: go-m
        command: tail -F anything
        depends_on:
            - pgsql
        ports:
            - "5000:5000"
        volumes:
            - ../app:/var/www/service-poll
            - ./go:/go
        networks:
            - backend

    pgsql:
        image: postgres:16.1
        container_name: pg-m
        ports:
            - "5432:5432"
        volumes:
            - ./db:/var/lib/postgresql/data
        environment:
            POSTGRES_PASSWORD: IiHOvNg3CZwS
            POSTGRES_USER: u-poll
        networks:
            - backend    

    pgadmin:
        image: dpage/pgadmin4
        container_name: pgadmin-m
        restart: always
        depends_on:
            - pgsql
        ports:
            - "5050:80"
        environment:
            PGADMIN_DEFAULT_EMAIL: nebudetvlom@gmail.com
            PGADMIN_DEFAULT_PASSWORD: admin
        volumes:
            - ./pgadmin:/var/lib/pgadmin
        networks:
            - backend

networks:
    backend: